### ISSUE TITLE
Fake issue

### ISSUE THREAD

**Issue by CleoQc** [bluciam/helloworld_pyladiesMTL#10]
Just testing

**Comment by OrganicNN** [comment]
There are so many issues!

**Comment by TrishGillett** [comment]
Fake issues are a real problem... :P

**Comment by kshred** [comment]
As if we didn't already have enough real issues...

**Comment by bastientalgorn** [comment]
Ive got 99 problems but github ain't one.

**Comment by nastaranj** [comment]
I'm testing too .. :+1:

**Comment by Sarahjdes** [comment]
:smile_cat: The guys at my office will kill me once I start putting emojis everywhere!

**Comment by CleoQc** [comment]
:snake: 

:snowflake: is coming

**Comment by bluciam** [comment]
Given that is fake, we don't need it anymore!
